# First Steps with xlwings

## Using xlwings as a Data Viewer

In [1]:
import xlwings as xw
import pandas as pd
import numpy as np

__numpy array__

In [2]:
data1 = np.random.randint(1, 100, 10000).reshape(100, 100)

In [3]:
data1#.shape

array([[68,  1, 78, ..., 92, 90, 36],
       [32, 95, 57, ..., 47, 17, 56],
       [ 5, 14, 55, ..., 47, 94, 73],
       ...,
       [97, 40, 88, ..., 67,  7, 27],
       [28, 52, 39, ..., 50, 83, 17],
       [65, 27, 26, ..., 58, 62,  8]])

In [7]:
xw.view(data1)

In [5]:
data2 = np.random.randint(1, 100, 100).reshape(10, 10)
data2

array([[13, 55, 70, 52, 43,  2, 65, 20, 40,  7],
       [ 6, 64, 87, 92, 45, 52, 87, 91, 35, 13],
       [46, 49, 52, 13, 97,  1, 59, 57, 33, 73],
       [21, 44, 32, 84, 26, 53, 89, 48, 18, 63],
       [61, 53, 42, 20,  9, 85, 12, 78, 51, 82],
       [93, 81, 49, 88, 10, 88, 98, 99, 32, 55],
       [11, 86, 32, 18, 35, 61, 44, 91, 73, 63],
       [60,  3, 14, 98, 92, 52, 49, 26, 58, 16],
       [ 6, 90, 58, 41,  2, 66, 33, 36, 69, 27],
       [45, 94, 29, 57, 90, 42, 92,  3, 22, 39]])

In [6]:
xw.view(data2)

In [8]:
xw.view(data2, sheet = xw.sheets.active)

__Pandas DataFrame__

In [9]:
df = pd.read_csv("titanic.csv")

In [12]:
df

     survived  pclass     sex    age  sibsp  parch      fare embarked deck
0           0       3    male  22.00      1      0    7.2500        S  NaN
1           1       1  female  38.00      1      0   71.2833        C    C
2           1       3  female  26.00      0      0    7.9250        S  NaN
3           1       1  female  35.00      1      0   53.1000        S    C
4           0       3    male  35.00      0      0    8.0500        S  NaN
5           0       3    male    NaN      0      0    8.4583        Q  NaN
6           0       1    male  54.00      0      0   51.8625        S    E
7           0       3    male   2.00      3      1   21.0750        S  NaN
8           1       3  female  27.00      0      2   11.1333        S  NaN
9           1       2  female  14.00      1      0   30.0708        C  NaN
10          1       3  female   4.00      1      1   16.7000        S    G
11          1       1  female  58.00      0      0   26.5500        S    C
12          0       3    male  20.00      0      0    8.0500        S  NaN
13          0       3    male  39.00      1      5   31.2750        S  NaN
14          0       3  female  14.00      0      0    7.8542        S  NaN
15          1       2  female  55.00      0      0   16.0000        S  NaN
16          0       3    male   2.00      4      1   29.1250        Q  NaN
17          1       2    male    NaN      0      0   13.0000        S  NaN
18          0       3  female  31.00      1      0   18.0000        S  NaN
19          1       3  female    NaN      0      0    7.2250        C  NaN
20          0       2    male  35.00      0      0   26.0000        S  NaN
21          1       2    male  34.00      0      0   13.0000        S    D
22          1       3  female  15.00      0      0    8.0292        Q  NaN
23          1       1    male  28.00      0      0   35.5000        S    A
24          0       3  female   8.00      3      1   21.0750        S  NaN
25          1       3  female  38.00      1      5   31.3875        S  NaN
26          0       3    male    NaN      0      0    7.2250        C  NaN
27          0       1    male  19.00      3      2  263.0000        S    C
28          1       3  female    NaN      0      0    7.8792        Q  NaN
29          0       3    male    NaN      0      0    7.8958        S  NaN
30          0       1    male  40.00      0      0   27.7208        C  NaN
31          1       1  female    NaN      1      0  146.5208        C    B
32          1       3  female    NaN      0      0    7.7500        Q  NaN
33          0       2    male  66.00      0      0   10.5000        S  NaN
34          0       1    male  28.00      1      0   82.1708        C  NaN
35          0       1    male  42.00      1      0   52.0000        S  NaN
36          1       3    male    NaN      0      0    7.2292        C  NaN
37          0       3    male  21.00      0      0    8.0500        S  NaN
38          0       3  female  18.00      2      0   18.0000        S  NaN
39          1       3  female  14.00      1      0   11.2417        C  NaN
40          0       3  female  40.00      1      0    9.4750        S  NaN
41          0       2  female  27.00      1      0   21.0000        S  NaN
42          0       3    male    NaN      0      0    7.8958        C  NaN
43          1       2  female   3.00      1      2   41.5792        C  NaN
44          1       3  female  19.00      0      0    7.8792        Q  NaN
45          0       3    male    NaN      0      0    8.0500        S  NaN
46          0       3    male    NaN      1      0   15.5000        Q  NaN
47          1       3  female    NaN      0      0    7.7500        Q  NaN
48          0       3    male    NaN      2      0   21.6792        C  NaN
49          0       3  female  18.00      1      0   17.8000        S  NaN
50          0       3    male   7.00      4      1   39.6875        S  NaN
51          0       3    male  21.00      0      0    7.8000        S  NaN
52          1       1  female  49.00      1      0   76.7292        C    D
53          1       2  female  29.00      1      0   26.0000        S  NaN
54          0       1    male  65.00      0      1   61.9792        C    B
55          1       1    male    NaN      0      0   35.5000        S    C
56          1       2  female  21.00      0      0   10.5000        S  NaN
57          0       3    male  28.50      0      0    7.2292        C  NaN
58          1       2  female   5.00      1      2   27.7500        S  NaN
59          0       3    male  11.00      5      2   46.9000        S  NaN
60          0       3    male  22.00      0      0    7.2292        C  NaN
61          1       1  female  38.00      0      0   80.0000      NaN    B
62          0       1    male  45.00      1      0   83.4750        S    C
63          0       3    male   4.00      3      2   27.9000        S  NaN
64          0       1    male    NaN      0      0   27.7208        C  NaN
65          1       3    male    NaN      1      1   15.2458        C  NaN
66          1       2  female  29.00      0      0   10.5000        S    F
67          0       3    male  19.00      0      0    8.1583        S  NaN
68          1       3  female  17.00      4      2    7.9250        S  NaN
69          0       3    male  26.00      2      0    8.6625        S  NaN
70          0       2    male  32.00      0      0   10.5000        S  NaN
71          0       3  female  16.00      5      2   46.9000        S  NaN
72          0       2    male  21.00      0      0   73.5000        S  NaN
73          0       3    male  26.00      1      0   14.4542        C  NaN
74          1       3    male  32.00      0      0   56.4958        S  NaN
75          0       3    male  25.00      0      0    7.6500        S    F
76          0       3    male    NaN      0      0    7.8958        S  NaN
77          0       3    male    NaN      0      0    8.0500        S  NaN
78          1       2    male   0.83      0      2   29.0000        S  NaN
79          1       3  female  30.00      0      0   12.4750        S  NaN
80          0       3    male  22.00      0      0    9.0000        S  NaN
81          1       3    male  29.00      0      0    9.5000        S  NaN
82          1       3  female    NaN      0      0    7.7875        Q  NaN
83          0       1    male  28.00      0      0   47.1000        S  NaN
84          1       2  female  17.00      0      0   10.5000        S  NaN
85          1       3  female  33.00      3      0   15.8500        S  NaN
86          0       3    male  16.00      1      3   34.3750        S  NaN
87          0       3    male    NaN      0      0    8.0500        S  NaN
88          1       1  female  23.00      3      2  263.0000        S    C
89          0       3    male  24.00      0      0    8.0500        S  NaN
90          0       3    male  29.00      0      0    8.0500        S  NaN
91          0       3    male  20.00      0      0    7.8542        S  NaN
92          0       1    male  46.00      1      0   61.1750        S    E
93          0       3    male  26.00      1      2   20.5750        S  NaN
94          0       3    male  59.00      0      0    7.2500        S  NaN
95          0       3    male    NaN      0      0    8.0500        S  NaN
96          0       1    male  71.00      0      0   34.6542        C    A
97          1       1    male  23.00      0      1   63.3583        C    D
98          1       2  female  34.00      0      1   23.0000        S  NaN
99          0       2    male  34.00      1      0   26.0000        S  NaN
100         0       3  female  28.00      0      0    7.8958        S  NaN
101         0       3    male    NaN      0      0    7.8958        S  NaN
102         0       1    male  21.00      0      1   77.2875        S    D
103         0       3    male  33.00      0      0    8.6542        S  NaN
104         0       3    male  37.00      2      0    7.9250        S  NaN
105         0       3    male  28.00      0      0    7.8958        S  NaN
106         1       3  female  21.00      0      0    7.6500        S  NaN
107         1       3    male    NaN      0      0    7.7750        S  NaN
108         0       3    male  38.00      0      0    7.8958        S  NaN
109         1       3  female    NaN      1      0   24.1500        Q  NaN
110         0       1    male  47.00      0      0   52.0000        S    C
111         0       3  female  14.50      1      0   14.4542        C  NaN
112         0       3    male  22.00      0      0    8.0500        S  NaN
113         0       3  female  20.00      1      0    9.8250        S  NaN
114         0       3  female  17.00      0      0   14.4583        C  NaN
115         0       3    male  21.00      0      0    7.9250        S  NaN
116         0       3    male  70.50      0      0    7.7500        Q  NaN
117         0       2    male  29.00      1      0   21.0000        S  NaN
118         0       1    male  24.00      0      1  247.5208        C    B
119         0       3  female   2.00      4      2   31.2750        S  NaN
120         0       2    male  21.00      2      0   73.5000        S  NaN
121         0       3    male    NaN      0      0    8.0500        S  NaN
122         0       2    male  32.50      1      0   30.0708        C  NaN
123         1       2  female  32.50      0      0   13.0000        S    E
124         0       1    male  54.00      0      1   77.2875        S    D
125         1       3    male  12.00      1      0   11.2417        C  NaN
126         0       3    male    NaN      0      0    7.7500        Q  NaN
127         1       3    male  24.00      0      0    7.1417        S  NaN
128         1       3  female    NaN      1      1   22.3583        C    F
129         0       3    male  45.00      0      0    6.9750        S  NaN
130         0       3    male  33.00      0      0    7.8958        C  NaN
131         0       3    male  20.00      0      0    7.0500        S  NaN
132         0       3  female  47.00      1      0   14.5000        S  NaN
133         1       2  female  29.00      1      0   26.0000        S  NaN
134         0       2    male  25.00      0      0   13.0000        S  NaN
135         0       2    male  23.00      0      0   15.0458        C  NaN
136         1       1  female  19.00      0      2   26.2833        S    D
137         0       1    male  37.00      1      0   53.1000        S    C
138         0       3    male  16.00      0      0    9.2167        S  NaN
139         0       1    male  24.00      0      0   79.2000        C    B
140         0       3  female    NaN      0      2   15.2458        C  NaN
141         1       3  female  22.00      0      0    7.7500        S  NaN
142         1       3  female  24.00      1      0   15.8500        S  NaN
143         0       3    male  19.00      0      0    6.7500        Q  NaN
144         0       2    male  18.00      0      0   11.5000        S  NaN
145         0       2    male  19.00      1      1   36.7500        S  NaN
146         1       3    male  27.00      0      0    7.7958        S  NaN
147         0       3  female   9.00      2      2   34.3750        S  NaN
148         0       2    male  36.50      0      2   26.0000        S    F
149         0       2    male  42.00      0      0   13.0000        S  NaN
150         0       2    male  51.00      0      0   12.5250        S  NaN
151         1       1  female  22.00      1      0   66.6000        S    C
152         0       3    male  55.50      0      0    8.0500        S  NaN
153         0       3    male  40.50      0      2   14.5000        S  NaN
154         0       3    male    NaN      0      0    7.3125        S  NaN
155         0       1    male  51.00      0      1   61.3792        C  NaN
156         1       3  female  16.00      0      0    7.7333        Q  NaN
157         0       3    male  30.00      0      0    8.0500        S  NaN
158         0       3    male    NaN      0      0    8.6625        S  NaN
159         0       3    male    NaN      8      2   69.5500        S  NaN
160         0       3    male  44.00      0      1   16.1000        S  NaN
161         1       2  female  40.00      0      0   15.7500        S  NaN
162         0       3    male  26.00      0      0    7.7750        S  NaN
163         0       3    male  17.00      0      0    8.6625        S  NaN
164         0       3    male   1.00      4      1   39.6875        S  NaN
165         1       3    male   9.00      0      2   20.5250        S  NaN
166         1       1  female    NaN      0      1   55.0000        S    E
167         0       3  female  45.00      1      4   27.9000        S  NaN
168         0       1    male    NaN      0      0   25.9250        S  NaN
169         0       3    male  28.00      0      0   56.4958        S  NaN
170         0       1    male  61.00      0      0   33.5000        S    B
171         0       3    male   4.00      4      1   29.1250        Q  NaN
172         1       3  female   1.00      1      1   11.1333        S  NaN
173         0       3    male  21.00      0      0    7.9250        S  NaN
174         0       1    male  56.00      0      0   30.6958        C    A
175         0       3    male  18.00      1      1    7.8542        S  NaN
176         0       3    male    NaN      3      1   25.4667        S  NaN
177         0       1  female  50.00      0      0   28.7125        C    C
178         0       2    male  30.00      0      0   13.0000        S  NaN
179         0       3    male  36.00      0      0    0.0000        S  NaN
180         0       3  female    NaN      8      2   69.5500        S  NaN
181         0       2    male    NaN      0      0   15.0500        C  NaN
182         0       3    male   9.00      4      2   31.3875        S  NaN
183         1       2    male   1.00      2      1   39.0000        S    F
184         1       3  female   4.00      0      2   22.0250        S  NaN
185         0       1    male    NaN      0      0   50.0000        S    A
186         1       3  female    NaN      1      0   15.5000        Q  NaN
187         1       1    male  45.00      0      0   26.5500        S  NaN
188         0       3    male  40.00      1      1   15.5000        Q  NaN
189         0       3    male  36.00      0      0    7.8958        S  NaN
190         1       2  female  32.00      0      0   13.0000        S  NaN
191         0       2    male  19.00      0      0   13.0000        S  NaN
192         1       3  female  19.00      1      0    7.8542        S  NaN
193         1       2    male   3.00      1      1   26.0000        S    F
194         1       1  female  44.00      0      0   27.7208        C    B
195         1       1  female  58.00      0      0  146.5208        C    B
196         0       3    male    NaN      0      0    7.7500        Q  NaN
197         0       3    male  42.00      0      1    8.4042        S  NaN
198         1       3  female    NaN      0      0    7.7500        Q  NaN
199         0       2  female  24.00      0      0   13.0000        S  NaN
200         0       3    male  28.00      0      0    9.5000        S  NaN
201         0       3    male    NaN      8      2   69.5500        S  NaN
202         0       3    male  34.00      0      0    6.4958        S  NaN
203         0       3    male  45.50      0      0    7.2250        C  NaN
204         1       3    male  18.00      0      0    8.0500        S  NaN
205         0       3  female   2.00      0      1   10.4625        S    G
206         0       3    male  32.00      1      0   15.8500        S  NaN
207         1       3    male  26.00      0      0   18.7875        C  NaN
208         1       3  female  16.00      0      0    7.7500        Q  NaN
209         1       1    male  40.00      0      0   31.0000        C    A
210         0       3    male  24.00      0      0    7.0500        S  NaN
211         1       2  female  35.00      0      0   21.0000        S  NaN
212         0       3    male  22.00      0      0    7.2500        S  NaN
213         0       2    male  30.00      0      0   13.0000        S  NaN
214         0       3    male    NaN      1      0    7.7500        Q  NaN
215         1       1  female  31.00      1      0  113.2750        C    D
216         1       3  female  27.00      0      0    7.9250        S  NaN
217         0       2    male  42.00      1      0   27.0000        S  NaN
218         1       1  female  32.00      0      0   76.2917        C    D
219         0       2    male  30.00      0      0   10.5000        S  NaN
220         1       3    male  16.00      0      0    8.0500        S  NaN
221         0       2    male  27.00      0      0   13.0000        S  NaN
222         0       3    male  51.00      0      0    8.0500        S  NaN
223         0       3    male    NaN      0      0    7.8958        S  NaN
224         1       1    male  38.00      1      0   90.0000        S    C
225         0       3    male  22.00      0      0    9.3500        S  NaN
226         1       2    male  19.00      0      0   10.5000        S  NaN
227         0       3    male  20.50      0      0    7.2500        S  NaN
228         0       2    male  18.00      0      0   13.0000        S  NaN
229         0       3  female    NaN      3      1   25.4667        S  NaN
230         1       1  female  35.00      1      0   83.4750        S    C
231         0       3    male  29.00      0      0    7.7750        S  NaN
232         0       2    male  59.00      0      0   13.5000        S  NaN
233         1       3  female   5.00      4      2   31.3875        S  NaN
234         0       2    male  24.00      0      0   10.5000        S  NaN
235         0       3  female    NaN      0      0    7.5500        S  NaN
236         0       2    male  44.00      1      0   26.0000        S  NaN
237         1       2  female   8.00      0      2   26.2500        S  NaN
238         0       2    male  19.00      0      0   10.5000        S  NaN
239         0       2    male  33.00      0      0   12.2750        S  NaN
240         0       3  female    NaN      1      0   14.4542        C  NaN
241         1       3  female    NaN      1      0   15.5000        Q  NaN
242         0       2    male  29.00      0      0   10.5000        S  NaN
243         0       3    male  22.00      0      0    7.1250        S  NaN
244         0       3    male  30.00      0      0    7.2250        C  NaN
245         0       1    male  44.00      2      0   90.0000        Q    C
246         0       3  female  25.00      0      0    7.7750        S  NaN
247         1       2  female  24.00      0      2   14.5000        S  NaN
248         1       1    male  37.00      1      1   52.5542        S    D
249         0       2    male  54.00      1      0   26.0000        S  NaN
250         0       3    male    NaN      0      0    7.2500        S  NaN
251         0       3  female  29.00      1      1   10.4625        S    G
252         0       1    male  62.00      0      0   26.5500        S    C
253         0       3    male  30.00      1      0   16.1000        S  NaN
254         0       3  female  41.00      0      2   20.2125        S  NaN
255         1       3  female  29.00      0      2   15.2458        C  NaN
256         1       1  female    NaN      0      0   79.2000        C  NaN
257         1       1  female  30.00      0      0   86.5000        S    B
258         1       1  female  35.00      0      0  512.3292        C  NaN
259         1       2  female  50.00      0      1   26.0000        S  NaN
260         0       3    male    NaN      0      0    7.7500        Q  NaN
261         1       3    male   3.00      4      2   31.3875        S  NaN
262         0       1    male  52.00      1      1   79.6500        S    E
263         0       1    male  40.00      0      0    0.0000        S    B
264         0       3  female    NaN      0      0    7.7500        Q  NaN

In [11]:
pd.options.display.max_rows = 900

In [13]:
xw.view(df)

## Connecting to a Book

In [14]:
import xlwings as xw

### 1. Open a new Book

In [15]:
xw.Book()

In [16]:
xw.books.active

In [17]:
xw.books.active.close()

In [18]:
wb = xw.Book()

In [19]:
wb

In [20]:
wb.close()

### 2. Connect to an open, unsaved Book

In [21]:
wb = xw.Book("Book1")
wb

### 3. Connect to a saved Book

In [28]:
r"C:\Users\benja\OneDrive\Desktop\Test1.xlsx"

'C:\\Users\\benja\\OneDrive\\Desktop\\Test1.xlsx'

In [32]:
path = r"C:\Users\benja\OneDrive\Desktop\Test1.xlsx" #Windows

In [ ]:
#path = "/Users/hagma_w/Desktop/Test1.xlsx" #macOS and Linux

In [33]:
wb = xw.Book(path)
wb

In [34]:
wb = xw.Book("Test2.xlsx")
wb

## Reading and Writing single Values

In [1]:
import xlwings as xw

In [2]:
wb = xw.Book()
wb

In [3]:
sheet = wb.sheets[0]
sheet

In [4]:
xw.books.active

In [5]:
xw.sheets.active

### Writing a single Value

In [6]:
sheet.range("A1").value = "Hello World" # strings

### Reading a single Value

In [7]:
sheet.range("A1").value

'Hello World'

In [8]:
sheet.range("A1")

In [9]:
sheet.range((1, 1)).value

'Hello World'

In [10]:
sheet.range((1, 2)).value = 123 # numerical values

In [11]:
sheet.range("B1").value

123.0

In [12]:
int(sheet.range("B1").value)

123

In [13]:
sheet.range((2, 4)).value = 666 # numerical values

__datetime objects__

In [14]:
import datetime as dt

In [15]:
date = dt.datetime(2020, 3, 20, 15, 30, 45)
date

datetime.datetime(2020, 3, 20, 15, 30, 45)

In [17]:
sheet.range("A2").value = date # datetime objects

In [18]:
sheet.range("A2").value

datetime.datetime(2020, 3, 20, 15, 30, 45)

In [19]:
sheet.range("A1").clear_contents()

## Assigning a Name (named ranges)

In [30]:
sheet.range("A1").value = 1000

In [31]:
sheet.range("A1").value

1000.0

In [32]:
sheet.range("A1").name = "Number"

In [35]:
sheet.range("Number").value

1000.0

In [36]:
sheet.range("Number").name

## Writing Excel Functions with Python

In [37]:
import xlwings as xw

In [38]:
wb = xw.Book()
wb

In [41]:
sheet = wb.sheets[0]
sheet

In [44]:
sheet.range("A1").value = 1

In [45]:
sheet.range("A2").value = 2

In [46]:
sheet.range("A3").formula = "=SUM(A1:A2)"

In [47]:
sheet.range("A3").value

3.0

In [48]:
sheet.range("A3").formula

'=SUM(A1:A2)'

In [49]:
sheet.range("B1").formula = "=A1"

In [50]:
sheet.range("B1").formula

'=A1'

## Range Shortcuts

In [51]:
import xlwings as xw

In [52]:
wb = xw.Book()
wb

In [53]:
sheet = wb.sheets[0]
sheet

In [54]:
sheet.range("A1").value = 100

In [55]:
sheet.range("A1").value

100.0

In [56]:
sheet["B1"].value = 100

In [57]:
sheet["B1"].value

100.0

## Case Study - bringing it all together

In [60]:
import xlwings as xw
import numpy as np

In [61]:
wb = xw.Book("CaseStudy_1.xlsx")
wb

In [62]:
sheet = wb.sheets[0]
sheet

In [63]:
sheet.range("B1").name = "Saving"

In [64]:
sheet.range("B2").name = "Interest_Rate"

In [65]:
sheet.range("B3").name = "Periods"

In [66]:
sheet.range("B4").name = "Future_Value"

In [68]:
fv = -np.fv(rate = sheet.range("Interest_Rate").value, 
            nper = sheet.range("Periods").value, 
            pmt = 0, 
            pv = sheet.range("Saving").value
           )

<ipython-input-68-99ca7700fa38>:1: DeprecationWarning: numpy.fv is deprecated and will be removed from NumPy 1.20. Use numpy_financial.fv instead (https://pypi.org/project/numpy-financial/).
  fv = -np.fv(rate = sheet.range("Interest_Rate").value,

In [69]:
fv

121.55062500000003

In [70]:
sheet.range("Future_Value").value = fv

# Homework

Import the required Library.

In [73]:
import xlwings as xw
import numpy as np

Open a new workbook and create a conncetion to that workbook with xlwings. Create a sheet object.

In [75]:
wb = xw.Book()

In [78]:
sheet = wb.sheets[0]

Type two numbers of your choice into the cells A1 and B1 (no Python Code required).

Create named ranges for both cells and read the values into Python with xlwings.

In [83]:
sheet.range("A1").name = "Number1"

In [84]:
sheet.range("B1").name = "Number2"

In [90]:
int(sheet.range("Number1").value)

5

In [89]:
int(sheet.range("Number2").value)

6

Move the cells in Excel and change their values (no Python Code required).

Read the values into Python, calculate the sum in Python, and write the sum into any other cell with xlwings.

In [91]:
add_numbers = sheet.range('Number1').value + sheet.range("Number2").value

In [92]:
add_numbers

12.0

In [93]:
sheet.range("F10").value = add_numbers

Open the Excel file "Test2.xlsx" and change the value in cell C1 from 2 to "two".

In [94]:
wb = xw.Book("Test2.xlsx")

In [95]:
sheet = wb.sheets[0]

In [96]:
sheet.range("C1").value ="two"

Try to create an xlwings connection to any excel workboook of your choice on your computer and read and write values.

In [102]:
path = r"C:\Users\benja\OneDrive\Desktop\2.0 Group\Soccer Model.xlsm"

In [104]:
wb =xw.Book(path)

# +++ Stop here, if you don´t want to see the Solution! +++

----------------------------

## Homework Solution

Import the required Library.

In [ ]:
import xlwings as xw

Open a new workbook and create a conncetion to that workbook with xlwings. Create a sheet object.

In [ ]:
wb = xw.Book()

In [ ]:
sheet = wb.sheets[0]

Type two numbers of your choice into the cells A1 and B1 (no Python Code required).

Create named ranges for both cells and read the values into Python with xlwings.

In [ ]:
sheet.range("A1").name = "Number1"

In [ ]:
sheet.range("B1").name = "Number2"

In [ ]:
sheet.range("Number1").value

In [ ]:
sheet.range("Number2").value

Move the cells in Excel and change their values (no Python Code required).

Read the values into Python, calculate the sum in Python, and write the sum into any other cell with xlwings.

In [ ]:
add_numbers = sheet.range("Number1").value + sheet.range("Number2").value

In [ ]:
add_numbers

In [ ]:
sheet.range("F10").value = add_numbers

Open the Excel file "Test2.xlsx" and change the value in cell C1 from 2 to "two".

In [ ]:
wb = xw.Book("Test2.xlsx")

In [ ]:
sheet = wb.sheets[0]

In [ ]:
sheet.range("C1").value = "two"

Try to create an xlwings connection to any excel workboook of your choice on your computer and read and write values.

In [ ]:
# see Lecture "How to connect to a workbook" (connect to a saved book)